name: Close PR

on:
  pull_request:
    types: [opened, reopened]

permissions:
  pull-requests: write

jobs:
  close-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            await github.rest.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
              state: 'closed'
            });
