name: Publish

on:
  workflow_dispatch:

jobs:
  publish_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-go@v5
        with:
          go-version: '^1.25.2'

      - run: /home/linuxbrew/.linuxbrew/bin/brew install hugo
      - run: /home/linuxbrew/.linuxbrew/bin/hugo mod get -u
      - run: /home/linuxbrew/.linuxbrew/bin/hugo --gc --minify

      - uses: actions/upload-pages-artifact@v3
        id: deployment
        with:
          path: ./public/

  publish_deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      id-token: write
      pages: write
      contents: read
    runs-on: ubuntu-latest
    needs: publish_build
    steps:
      - uses: actions/deploy-pages@v4
        id: deployment
